"""empty message

Revision ID: 0e9839a45cbc
Revises: 97ebea23084f
Create Date: 2021-02-20 03:59:07.233700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9839a45cbc'
down_revision = '97ebea23084f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'name')
    # ### end Alembic commands ###
