"""empty message

Revision ID: ad7ab32bd6d4
Revises: 0e9839a45cbc
Create Date: 2021-02-21 00:12:58.744791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad7ab32bd6d4'
down_revision = '0e9839a45cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'name')
    op.add_column('user', sa.Column('photo', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo')
    op.add_column('posts', sa.Column('name', mysql.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
